// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/models/trade-stats.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TradeStatsProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	AvgPrice      float64                `protobuf:"fixed64,3,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	MinPrice      float64                `protobuf:"fixed64,4,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      float64                `protobuf:"fixed64,5,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeStatsProto) Reset() {
	*x = TradeStatsProto{}
	mi := &file_internal_models_trade_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeStatsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeStatsProto) ProtoMessage() {}

func (x *TradeStatsProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_trade_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeStatsProto.ProtoReflect.Descriptor instead.
func (*TradeStatsProto) Descriptor() ([]byte, []int) {
	return file_internal_models_trade_stats_proto_rawDescGZIP(), []int{0}
}

func (x *TradeStatsProto) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TradeStatsProto) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TradeStatsProto) GetAvgPrice() float64 {
	if x != nil {
		return x.AvgPrice
	}
	return 0
}

func (x *TradeStatsProto) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *TradeStatsProto) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

type MarketUpdateProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*TradeStatsProto     `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketUpdateProto) Reset() {
	*x = MarketUpdateProto{}
	mi := &file_internal_models_trade_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketUpdateProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketUpdateProto) ProtoMessage() {}

func (x *MarketUpdateProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_trade_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketUpdateProto.ProtoReflect.Descriptor instead.
func (*MarketUpdateProto) Descriptor() ([]byte, []int) {
	return file_internal_models_trade_stats_proto_rawDescGZIP(), []int{1}
}

func (x *MarketUpdateProto) GetStats() []*TradeStatsProto {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_internal_models_trade_stats_proto protoreflect.FileDescriptor

const file_internal_models_trade_stats_proto_rawDesc = "" +
	"\n" +
	"!internal/models/trade-stats.proto\x12\x06models\"\x96\x01\n" +
	"\x0fTradeStatsProto\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x1b\n" +
	"\tavg_price\x18\x03 \x01(\x01R\bavgPrice\x12\x1b\n" +
	"\tmin_price\x18\x04 \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x05 \x01(\x01R\bmaxPrice\"B\n" +
	"\x11MarketUpdateProto\x12-\n" +
	"\x05stats\x18\x01 \x03(\v2\x17.models.TradeStatsProtoR\x05statsB\x13Z\x11./internal/modelsb\x06proto3"

var (
	file_internal_models_trade_stats_proto_rawDescOnce sync.Once
	file_internal_models_trade_stats_proto_rawDescData []byte
)

func file_internal_models_trade_stats_proto_rawDescGZIP() []byte {
	file_internal_models_trade_stats_proto_rawDescOnce.Do(func() {
		file_internal_models_trade_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_models_trade_stats_proto_rawDesc), len(file_internal_models_trade_stats_proto_rawDesc)))
	})
	return file_internal_models_trade_stats_proto_rawDescData
}

var file_internal_models_trade_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_models_trade_stats_proto_goTypes = []any{
	(*TradeStatsProto)(nil),   // 0: models.TradeStatsProto
	(*MarketUpdateProto)(nil), // 1: models.MarketUpdateProto
}
var file_internal_models_trade_stats_proto_depIdxs = []int32{
	0, // 0: models.MarketUpdateProto.stats:type_name -> models.TradeStatsProto
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_models_trade_stats_proto_init() }
func file_internal_models_trade_stats_proto_init() {
	if File_internal_models_trade_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_models_trade_stats_proto_rawDesc), len(file_internal_models_trade_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_models_trade_stats_proto_goTypes,
		DependencyIndexes: file_internal_models_trade_stats_proto_depIdxs,
		MessageInfos:      file_internal_models_trade_stats_proto_msgTypes,
	}.Build()
	File_internal_models_trade_stats_proto = out.File
	file_internal_models_trade_stats_proto_goTypes = nil
	file_internal_models_trade_stats_proto_depIdxs = nil
}
