// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/v1/market.proto

package market

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TickStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         string                 `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	AvgPrice      string                 `protobuf:"bytes,3,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	MinPrice      string                 `protobuf:"bytes,4,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      string                 `protobuf:"bytes,5,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	IsVolumeSpike bool                   `protobuf:"varint,6,opt,name=is_volume_spike,json=isVolumeSpike,proto3" json:"is_volume_spike,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickStats) Reset() {
	*x = TickStats{}
	mi := &file_api_proto_v1_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickStats) ProtoMessage() {}

func (x *TickStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickStats.ProtoReflect.Descriptor instead.
func (*TickStats) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_market_proto_rawDescGZIP(), []int{0}
}

func (x *TickStats) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TickStats) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *TickStats) GetAvgPrice() string {
	if x != nil {
		return x.AvgPrice
	}
	return ""
}

func (x *TickStats) GetMinPrice() string {
	if x != nil {
		return x.MinPrice
	}
	return ""
}

func (x *TickStats) GetMaxPrice() string {
	if x != nil {
		return x.MaxPrice
	}
	return ""
}

func (x *TickStats) GetIsVolumeSpike() bool {
	if x != nil {
		return x.IsVolumeSpike
	}
	return false
}

type MarketSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*TickStats           `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketSnapshot) Reset() {
	*x = MarketSnapshot{}
	mi := &file_api_proto_v1_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketSnapshot) ProtoMessage() {}

func (x *MarketSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketSnapshot.ProtoReflect.Descriptor instead.
func (*MarketSnapshot) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_market_proto_rawDescGZIP(), []int{1}
}

func (x *MarketSnapshot) GetStats() []*TickStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_api_proto_v1_market_proto protoreflect.FileDescriptor

const file_api_proto_v1_market_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/v1/market.proto\x12\tmarket.v1\"\xb8\x01\n" +
	"\tTickStats\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x02 \x01(\tR\x05price\x12\x1b\n" +
	"\tavg_price\x18\x03 \x01(\tR\bavgPrice\x12\x1b\n" +
	"\tmin_price\x18\x04 \x01(\tR\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x05 \x01(\tR\bmaxPrice\x12&\n" +
	"\x0fis_volume_spike\x18\x06 \x01(\bR\risVolumeSpike\"<\n" +
	"\x0eMarketSnapshot\x12*\n" +
	"\x05stats\x18\x01 \x03(\v2\x14.market.v1.TickStatsR\x05statsB\"Z finstream/engine/internal/marketb\x06proto3"

var (
	file_api_proto_v1_market_proto_rawDescOnce sync.Once
	file_api_proto_v1_market_proto_rawDescData []byte
)

func file_api_proto_v1_market_proto_rawDescGZIP() []byte {
	file_api_proto_v1_market_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_market_proto_rawDesc), len(file_api_proto_v1_market_proto_rawDesc)))
	})
	return file_api_proto_v1_market_proto_rawDescData
}

var file_api_proto_v1_market_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_v1_market_proto_goTypes = []any{
	(*TickStats)(nil),      // 0: market.v1.TickStats
	(*MarketSnapshot)(nil), // 1: market.v1.MarketSnapshot
}
var file_api_proto_v1_market_proto_depIdxs = []int32{
	0, // 0: market.v1.MarketSnapshot.stats:type_name -> market.v1.TickStats
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_v1_market_proto_init() }
func file_api_proto_v1_market_proto_init() {
	if File_api_proto_v1_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_market_proto_rawDesc), len(file_api_proto_v1_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_v1_market_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_market_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_market_proto_msgTypes,
	}.Build()
	File_api_proto_v1_market_proto = out.File
	file_api_proto_v1_market_proto_goTypes = nil
	file_api_proto_v1_market_proto_depIdxs = nil
}
